### ISSUE TITLE
 failed to initialize KVM: Permission denied

### ISSUE THREAD

**Issue by skpeetha** [krystism/docker-nova-compute#1]
Host: ubuntu-trusty 14.04
Docker version 1.11.2

I fallowed the exact steps modified nothing. When I launch a instance from dashboard or CLI I see this error in the logs
`internal error: process exited while connecting to monitor: Could not access KVM kernel module: Permission denied\
nfailed to initialize KVM: Permission denied\`
`2016-07-19 13:52:59.792 27 TRACE nova.compute.manager [instance: 11841db0-0eaa-4d2f-950b-dd20cf2c2621] libvirtError: internal error: process exited whi
le connecting to monitor: Could not access KVM kernel module: Permission denied
2016-07-19 13:52:59.792 27 TRACE nova.compute.manager [instance: 11841db0-0eaa-4d2f-950b-dd20cf2c2621] failed to initialize KVM: Permission denied`

Is that a bug or problem with host machine?

**Comment by int32bit** [comment]
Yep, this project seems to be deprecated, you can use Openstack Kolla instead,  it can containlize most of Openstack Services.
